# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de8ab9d0a39127772ae8e4fdf6eaa7666861399fb54bfac19c0c530de60d964b2a446f1552bac0f07b3a167667558e604251fe0913f529378925958165eb6915

test:
  secret_key_base: 1e4d429adfef7157d5b30dc225b86461f32373657f0c9b879e5bb2ac82dd435f36eb8fb56e81f2626a70faf9eccf909f05cf3913b36f3d6aacecf242bd2c66d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
